{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "sec-ch-ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
    "cache-control": "no-cache",
    "sec-ch-ua-mobile": "?0",
    "postman-token": "7da708a0-45a1-2776-4d78-453cdb8fb851",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "sec-ch-ua-platform": "\"macOS\"",
    "accept": "*/*",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9,si;q=0.8"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/notes",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/api/notes",
  "listenerPath": "/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/notes",
  "uriParams": {},
  "rawRequestUri": "/api/notes",
  "rawRequestPath": "/api/notes",
  "remoteAddress": "/127.0.0.1:54932",
  "requestPath": "/api/notes"
}