#%RAML 1.0 NamedExample
NotesExample:
  -
    id: 1001
    titel: english
    content: this is an example content
    createAt: 2022-11-08T00:00:00.090Z
    updateAt: 2022-11-08T01:00:00.090Z
  -
    id: 1002
    titel: english
    content: this is an example content
    createAt: 2022-11-09T00:00:00.090Z
    updateAt: 2022-11-09T01:00:00.090Z